on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  USER1: bzhen
jobs:
  build:
     env:
       USER2: bzhen2
       USER1: bzhen1_job
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: step 2
         env:
           user3: bzhen3
           USER1: bzhen1_step
         run: |
          ls -l
          echo "github repo name is ${{ GITHUB.REPOSITORY }} and branch name is ${{ GITHUB.REF_NAME }} "
          echo "Value for variable user1, user2 and user3 are $USER1 $USER2 $user3"
          echo " Value for user1 and servername are ${{ vars.user1 }} and ${{ vars.server_name }}"
          pwd
          java -version
       - run: echo " Print value of user 3 $user3"
  test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: step 2
         run: |
          ls -l
          echo "github repo name is ${{ GITHUB.REPOSITORY }} and branch name is ${{ GITHUB.REF_NAME }} "
          echo "Value for variable user1, user2 and user3 are $USER1 $USER2 $user3"     
