name: workflow1
on: 
  push:
    branches:
      - main
      - development
      - hotfix
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - debug
        - warning
        - crtiical
  
jobs:
  job1:
     runs-on: ubuntu-latest
     steps:
       - name: Remarks
         run: uname -a
       - name: print hostname
         run: hostname 
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
       - run: sleep 30
       - run: echo "job1 and step 4 of job1 completed"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: |
            hostname
            sleep 10 
      - run: sleep 30
      - run: echo "job2 and step 4 of job2 completed"
