name: workflow1
on: 
  push:
    branches:
      - main
      - development
      - hotfix
  schedule:
    - cron: '55-59 10 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - debug
        - warning
        - crtiical
  
jobs:
  job1:
     runs-on: ubuntu-latest
     steps:
       - name: Remarks
         run: uname -a
       - name: print hostname
         run: hostname 
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
